apiVersion: v1
kind: Service
metadata:
  name: mongo-codex-svc
spec:
  type: {{ .Values.service.mongo.type }}
  ports:
    - port: {{ .Values.service.mongo.port }}
  selector:
    app: mongo-codex-svc
