apiVersion: v1
kind: Service
metadata:
  name: redis-codex-svc
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
  selector:
    app: redis-codex-svc
