apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roleName | default "codex-job-creator" }}
  namespace: {{ .Values.namespace | default "security-team" }}
rules:
- verbs:
    - create
  apiGroups:
    - batch
  resources:
    - jobs
