{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindingName | default "codex-job-creator-binding" }}
  namespace: {{ .Values.namespace | default "default" }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace | default "default" }}
roleRef:
  name: {{ .Values.roleName | default "codex-job-creator" }}
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- end }}