apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  aws_access_key_id: cmFuZG9tdGVzdGluZwo=  # Replace with base64-encoded value
  aws_secret_access_key: cmFuZG9tdGVzdGluZ3RoZWF3c3NlY3JldAo=  # Replace with base64-encoded value
  output: anNvbgo=  # "json" in base64
  region: dXMtZWFzdC0y  # "us-east-2" in base64
