apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codex-job-creator-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codex-job-creator
subjects:
- kind: ServiceAccount
  name: codex-sa
  namespace: default
